services:
#  db:
#    image: postgres:18-alpine
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_DB: ${POSTGRES_DB:-postgres}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app_db}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - app-network

  backend:
    build:
      context: ./backend
    image: app-backend:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5433/${POSTGRES_DB}
      CORS_ORIGINS: ${CORS_ORIGINS}
#    depends_on:
##      db:
##        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: app-frontend:latest
    ports:
      - "80:80"
    environment:
      VITE_APP_API_URL: http://155.212.147.208:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  postgres_data: